config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  before_validation { email.downcase! }
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]*\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('ログインが必要です')
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :destroy, :edit, :update]
  def new
    @blog = Blog.new
  end

  def index
    @blogs = Blog.all
  end

  def show
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    elsif @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end

  def edit
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    @blog.id = params[:id]
    render :index if @blog.invalid?
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end
 
  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "登録できました"
    else
      render :new
    end
  end

  def destroy
    @user = User.destroy(params[:id])
    redirect_to new_user_path
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def set_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: confirm_blogs_path) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="blog_image">
      <%= form.label :image %>
      <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit "投稿" %>
  <% end %>
  <%= link_to '一覧', blogs_path %>

app/views/blogs/confirm.html.erb
<h3>確認画面</h3>
<%= form_with(model: @blog, local: true, url: blogs_path)do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>投稿文:<%= @blog.content %></p>
  <p>投稿画像:<%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %></p>
  <%= f.hidden_field :image_cache %>
  <%= f.submit "投稿する" %>
  <%= f.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集</h1>
<%= form_with(model: @blog, local: true, url: blog_path) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="blog_title">
      <%= form.label :タイトル %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :投稿内容 %>
      <%= form.text_field :content %>
    </div>
    <div class="blog_image">
      <%= form.label :現在の投稿画像 %>
      <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
      <p>画像選択：<%= form.file_field :image %></p>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit "投稿" %>
  <% end %>
  <%= link_to '一覧', blogs_path %>

app/views/blogs/index.html.erb
<h1>一覧</h1>
<div><%= link_to '新規作成', new_blog_path %></div>
<% @blogs.each do |blog| %>
  <ul class="index">
    <div>
      <li>タイトル:<%= blog.title %></li>
    </div>
    <div>
      <li>投稿内容:<%= blog.content %></li>
    </div>
    <div>
      <li>投稿画像:<p><%= image_tag blog.image.url %></p></li>
    </div>
    <div>
      <li>投稿者:<%= blog.user.name %></li>
    </div>
    <div>
      <%= link_to '詳細', blog_path(blog.id) %>
      <%= link_to "編集", edit_blog_path(blog.id) %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data:{confirm: '本当に削除しますか？'} %>
    </div>
  </ul>
<% end %>

app/views/blogs/new.html.erb
<h1>新規作成</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>詳細</h1>
  <p>タイトル:<%= @blog.title %></p>
  <p>投稿内容：<%= @blog.content %></p>
  <p>投稿者：<%= @blog.user.name %></p>
  <p>画像：<%= image_tag @blog.image.url %></p>
<%= link_to '一覧', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1>FacebookClone</h1>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <div>ログイン中のユーザ：<%= current_user.name %></div>
        <div><%= link_to "ユーザ詳細", user_path(current_user.id) %>
             <%= link_to "ログアウト", session_path(current_user.id), method: :delete %></div>
        <%= link_to "投稿一覧", blogs_path %>
      <% else %>
        <ul>
          <li><%= link_to "ユーザ登録", new_user_path %></li>
          <li><%= link_to "ログイン", new_session_path %></li>
        </ul>
      <% end %>
    </header>
    <%= yield %>
    <footer>
      <p>Rails課題だよ</p>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>ユーザ登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation" >
    <h2> <%= @user.name %> ユーザの登録に失敗しました</h2>
    <ul>
      <% @user.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email%>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
  <% end %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <div>
    <p><%= flash[:notice] %><p>
  </div>
<% end %>
<h3><%= @user.name %>のページ</h3>
<p>メールアドレス： <%= @user.email %></p>
<p><%= link_to "ユーザ削除", user_path(@user.id), method: :delete %></p>